# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 16:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('completed_on', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('reward_earned', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('R', 'Running'), ('P', 'Pending Verification'), ('A', 'Abandoned'), ('D', 'Disqualified')], max_length=1)),
                ('missions', models.ManyToManyField(to='missions.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSpecificData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lives', models.IntegerField(default=3)),
                ('squad_coins', models.FloatField(default=0)),
                ('missions', models.ManyToManyField(to='players.PlayerMissions')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('badge', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playerspecificdata',
            name='skills',
            field=models.ManyToManyField(to='players.Skills'),
        ),
        migrations.AddField(
            model_name='playerspecificdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
