# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 16:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company', models.CharField(max_length=30)),
                ('business_area', models.CharField(max_length=50)),
                ('last_published', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('billing_status', models.CharField(max_length=30)),
                ('plan_code', models.CharField(max_length=30)),
                ('squad_credits', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
    ]
