# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 16:56
from __future__ import unicode_literals

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='skills',
            field=models.ManyToManyField(to='players.Skills'),
        ),
        migrations.AddField(
            model_name='mission',
            name='updated_by',
            field=models.ForeignKey(default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instruction',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.Mission'),
        ),
    ]
