# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField()),
                ('user_gcm', models.CharField(max_length=2048)),
                ('text', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
